### PR TITLE
Change UIBarButton item to use UIBarButtonItemStylePlain and black co…

### PR DESCRIPTION
**Pull request by mjahn1**
…lor.

### CODE REVIEW

**Comment by DickyT** [comment]
great PR, thanks!

**Comment by DickyT** [comment]
Great PR, but why it is closed?

**Comment by mjahn1** [comment]
Did not mean to PR this. Was a specific style for something I need.  May be a good enhancement to abstract some of these styles into JS though!

**Comment by DickyT** [comment]
understand!

**Pull request closed without merging**
