### PR TITLE
fix for rn 0.40

### PR DESCRIPTION
**Pull request by evollu**

### CODE REVIEW

**Comment by DickyT** [comment]
@evollu Thank you for this PR. And I see there is no change to the javascript file, and it works on 0.40 only modifying the objc files? I have currently no react-native configured on my computer, I can merge this and publish to npm if it works completely fine on 0.40

**Comment by evollu** [comment]
yes. check breaking change note for 0.40.0 https://github.com/facebook/react-native/releases

**Comment by DickyT** [comment]
@evollu merged

**Comment by DickyT** [comment]
@evollu I also published the latest version `react-native-textinput-utils@0.3.7` to npm, you can try to use this package with `npm i --save` and see if there are any problems that need to be fixed.

**Comment by evollu** [comment]
looks good. thanks

**Pull request merged**
